### ISSUE TITLE
Default to Docker 1.13 when installing on RHEL 7.x

### ISSUE THREAD

**Issue by n0othing** [elastic/ansible-elastic-cloud-enterprise#79]
ECE is supported on RHEL 7 when using Docker 1.13 [1], however the playbook uses a default of `docker_version: "18.09"` [2], which means users can end up with an unsupported installation if they don't adjust the `docker_version` variable. It'd be great if we could default to `1.13` (maybe even prohibit `18.09` [3]?) if installing on RHEL 7.

[1] https://www.elastic.co/guide/en/cloud-enterprise/current/ece-prereqs-software-linux.html
[2]  https://github.com/elastic/ansible-elastic-cloud-enterprise/blob/master/defaults/main.yml#L11
[3] https://github.com/elastic/ansible-elastic-cloud-enterprise/blob/master/tasks/base/RedHat-7/install_docker.yml#L24-L36

**Comment by obierlaire** [comment]
Yes, this is confusing:
- according to the playbook, we could install docker 18 on rhel 7 even contrary to our [prerequistes](https://www.elastic.co/guide/en/cloud-enterprise/current/ece-prereqs-software-linux.html) 
- the playbook defaults docker 18 for RHEL, which is not the version we officially support
- the playbook forces 18 for all OS, even if we are now supporting docker 19 for some distributions

@Kushmaro , maybe we could:
- [ ] remove everything related to docker 18 for RHEL 7
- [ ] have the default version of docker per distribution, instead of a global default

**Comment by Kushmaro** [comment]
@obierlaire Sounds good to me.

**Comment by obierlaire** [comment]
https://github.com/elastic/ansible-elastic-cloud-enterprise/pull/98 has been merged. We can close this issue.
