### ISSUE TITLE
Playbook fails on Ubuntu when docker not installed

### ISSUE THREAD

**Issue by rhass** [elastic/ansible-elastic-cloud-enterprise#85]
In my efforts to reproduce a different issue, I have identified a problem with the playbook installing docker. It appears we assert docker to be installed before it is able to attempt to install the desired version.

I believe this the issue is we attempt to validate the docker version BEFORE we attempt to install docker.
https://github.com/elastic/ansible-elastic-cloud-enterprise/blob/master/tasks/base/main.yml#L8-L11

However, ansible throws an error before we can do anything about it.

**Comment by vaubarth** [comment]
Which version of ubuntu are you trying to run the playbooks against? Maybe it was just a linking issue but the task that you linked to checks if the OS version is supported.

**Comment by rhass** [comment]
Ubuntu 18.04. Ubuntu 20.04 had other issues, but I opted not to put effort into it. This may have been caused by an environment issue, in which I was attempting to run in a vagrant VM. I later realized this playbook won't work outside of AWS due to use of the metadata service.

**Comment by vaubarth** [comment]
It shouldn't be tied to any cloud provider... if a dependency snuck in that would be a bug. Can you link me to the part where that is?

**Comment by deepybee** [comment]
This fails because the assertion is that the _proposed_ Docker version _to be installed_ matches the supported version for the target host.

The variable `docker_version` is declared in from `defaults/main.yml`; the dict lookup expects a key of its default value, `18.09`, as specified in `defaults/main.yml` but the only key in the dict in `vars/os_Ubuntu_18.yml` is `19.03`.

`18.03` is the correct version for two of the supported OS's;

|OS|Supported Docker version|
|---|---------------|
|CentOS 7|1.13|
|CentOS 8|19.03|
|RHEL 7|1.13|
|RHEL 8|19.03|
|SLES 12|18.09|
|Ubuntu 16.04|18.09|
|Ubuntu 18.04|19.03|

```
TASK [ansible-elastic-cloud-enterprise : Assert docker version is supported] *******************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: [REDACTED]/ansible-elastic-cloud-enterprise/tasks/base/main.yml:13
fatal: [192.168.1.17]: FAILED! => {
    "assertion": "docker_version in docker_version_map.keys()",
    "changed": false,
    "evaluated_to": false,
    "msg": "Docker version must be one of dict_keys(['19.03'])"
}
```

Setting `docker_version: "19.03"` in a `group_vars/all.yml` overrides the default.

```
TASK [ansible-elastic-cloud-enterprise : Assert docker version is supported] *******************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: [REDACTED]/ansible-elastic-cloud-enterprise/tasks/base/main.yml:13
ok: [192.168.1.17] => {
    "changed": false,
    "msg": "All assertions passed"
}
```

> Ubuntu 20.04 had other issues, but I opted not to put effort into it.

That failure is by design, Ubuntu 20.04 is not a [supported OS](https://www.elastic.co/guide/en/cloud-enterprise/current/ece-prereqs-software-linux.html#ece-prereqs-software-linux) for ECE at this time.

**Comment by obierlaire** [comment]
Thanks @deepybee for your detailed answer. I think we can close this
